spring:
  datasource:
    #url: jdbc:mysql://116.196.123.49:3306/star?useSSL=false&0characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/star?useSSL=false&0characterEncoding=utf8
    username: root
    password: wr000000
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 5
      max-wait: 300
  jpa:
    hibernate:
      ddl-auto: update
